package subway.domain;

import javax.persistence.*;

/**
 * create table station (
 * id bigint generated by default as identity,
 * name varchar(255) not null,
 * primary key (id)
 * )
 * 식별자를 가지는 클래스가 엔티티 클래스다
 * jpa 스펙자체가 protected 생성자를 좋아한다.
 * 프록시 빈 객체를 가지고 만들기 때문에
 */
@Entity
public class Station {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    public Station() {
    }

    protected Station(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
